# Generated by Django 3.0.4 on 2020-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150)),
                ('c_descp', models.CharField(max_length=500)),
                ('c_addr1', models.CharField(max_length=350)),
                ('c_addr2', models.CharField(max_length=350)),
                ('c_addr3', models.CharField(max_length=350)),
                ('c_pincode', models.CharField(max_length=50)),
                ('c_email', models.CharField(max_length=250)),
                ('c_contact1', models.CharField(max_length=50)),
                ('c_contact2', models.CharField(max_length=50)),
                ('c_url', models.CharField(max_length=250)),
                ('c_dt', models.CharField(max_length=50)),
                ('c_tm', models.CharField(max_length=50)),
                ('c_status', models.CharField(max_length=50)),
                ('c_logo', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_type', models.CharField(max_length=50)),
                ('data_path', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('company_details_id', models.IntegerField()),
                ('sub_category_master_id', models.IntegerField()),
                ('product_descp', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_master_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_master_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=350)),
                ('category_master_id', models.IntegerField()),
            ],
        ),
    ]
